# Generated by Django 4.2.4 on 2023-09-02 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bench',
            options={'verbose_name': 'Bank', 'verbose_name_plural': 'Baenke'},
        ),
        migrations.RemoveField(
            model_name='bench',
            name='description',
        ),
        migrations.AddField(
            model_name='bench',
            name='damages',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Beschädigungen'),
        ),
        migrations.AddField(
            model_name='bench',
            name='donation',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Spende von'),
        ),
        migrations.AddField(
            model_name='bench',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Datum der letzten Wartung'),
        ),
        migrations.AddField(
            model_name='bench',
            name='location_description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Standortbeschreibung'),
        ),
        migrations.AddField(
            model_name='bench',
            name='maintenance_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Beschreibung der benötigten Reperatur'),
        ),
        migrations.AddField(
            model_name='bench',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nummer der Bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bench',
            name='plastic_bench',
            field=models.BooleanField(default=False, verbose_name='Kunststoffbank'),
        ),
        migrations.AddField(
            model_name='bench',
            name='requires_maintenance',
            field=models.BooleanField(default=False, verbose_name='Benötigt Reperatur'),
        ),
        migrations.AddField(
            model_name='bench',
            name='type',
            field=models.IntegerField(choices=[(1, 'Bank'), (2, 'Schutzhütte')], default=1, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='bench',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='bench',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Längengrad'),
        ),
    ]
