# Generated by Django 4.2.4 on 2023-10-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_bench_options_remove_bench_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bench',
            name='maintenance_description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Anmerkungen zur Bank und Wartung'),
        ),
    ]
